name: GitHub Action

on:
  push:
  pull_request:
  release:
    types: [ created ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version:
          [
            "3.8",
            "3.9",
            "3.10",
            "3.11",
            "3.12",
            "3.13",
            "pypy3.8",
            "pypy3.9",
            "pypy3.10",
          ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install .

      - name: Test with unittest
        run: python -m unittest

    deploy:
      needs: test
      runs-on: ubuntu-latest
      if: github.event_name == 'release' && github.event.action == 'created'
      permissions:
        id-token: write
      steps:
        - uses: actions/checkout@v3

        - name: Install poetry
          run: pipx install poetry

        - name: Build Packages
          run: poetry build

        - name: Publish package distributions to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1